/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iss_trab_farmacia.view;

import iss_trab_farmacia.control.Pessoas;
import iss_trab_farmacia.entity.Pessoa;
import iss_trab_farmacia.util.Endereco;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;

/**
 *
 * @author guest-a2ok8M
 */
public class CadastroCliente extends javax.swing.JDialog {

    Pessoa pF;
    Pessoas pessoas = new Pessoas();
    
    /**
     * Creates new form CadastroCliente
     * @param parent
     * @param modal
     */
    public CadastroCliente(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        pF = new Pessoa();
    }
    
    public CadastroCliente(java.awt.Frame parent, boolean modal, Pessoa pF) {
        super(parent, modal);
        initComponents();
        
        this.pF = pF;
        
        this.txtNome.setText(pF.getNome());
        this.txtCpf.setText(pF.getCpf());
        this.emailCampo.setText(pF.getEmail());
        this.cidadeCampo.setText(pF.getEndereco().getCidade());
        this.cepCampo.setText(pF.getEndereco().getCEP());
        this.telefoneCampo.setText(pF.getTelefone());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lbEndereco = new javax.swing.JLabel();
        ruaEnderecoCampo = new javax.swing.JTextField();
        lbTelefone = new javax.swing.JLabel();
        salvarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        lbRua = new javax.swing.JLabel();
        lbNum = new javax.swing.JLabel();
        numeroEnderecoCampo = new javax.swing.JTextField();
        lbCep = new javax.swing.JLabel();
        lbCidade = new javax.swing.JLabel();
        cidadeCampo = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        emailCampo = new javax.swing.JTextField();
        lbCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        cepCampo = new javax.swing.JFormattedTextField();
        telefoneCampo = new javax.swing.JFormattedTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        erroImagem = new javax.swing.JLabel();
        erroImagem2 = new javax.swing.JLabel();
        erroImagem3 = new javax.swing.JLabel();
        erroImagem4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbNome.setText("Nome:");

        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lbEndereco.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbEndereco.setText("Endereço");

        ruaEnderecoCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruaEnderecoCampoActionPerformed(evt);
            }
        });

        lbTelefone.setText("Telefone");

        salvarBtn.setText("Salvar");
        salvarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        lbRua.setText("Rua:");

        lbNum.setText("Num:");

        lbCep.setText("CEP:");

        lbCidade.setText("Cidade");

        lbEmail.setText("E-mail:");

        lbCpf.setText("CPF:");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpfFocusLost(evt);
            }
        });
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });

        try {
            cepCampo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cepCampo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cepCampoFocusLost(evt);
            }
        });

        try {
            telefoneCampo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneCampo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefoneCampoFocusLost(evt);
            }
        });

        jCheckBox1.setText("Juridico");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        erroImagem.setIcon(new javax.swing.ImageIcon("/usuario/ISS_2016_Farmacia/ISS_Farmacia/src/main/java/iss_trab_farmacia/view/erro2.png")); // NOI18N
        erroImagem.setToolTipText("Mínimo de 3 caracteres");

        erroImagem2.setIcon(new javax.swing.ImageIcon("/usuario/ISS_2016_Farmacia/ISS_Farmacia/src/main/java/iss_trab_farmacia/view/erro2.png")); // NOI18N
        erroImagem2.setToolTipText("CPF inválido");

        erroImagem3.setIcon(new javax.swing.ImageIcon("/usuario/ISS_2016_Farmacia/ISS_Farmacia/src/main/java/iss_trab_farmacia/view/erro2.png")); // NOI18N
        erroImagem3.setToolTipText("Telefone Inválido");

        erroImagem4.setIcon(new javax.swing.ImageIcon("/usuario/ISS_2016_Farmacia/ISS_Farmacia/src/main/java/iss_trab_farmacia/view/erro2.png")); // NOI18N
        erroImagem4.setToolTipText("CEP inválido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCpf)
                            .addComponent(lbNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(erroImagem))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(erroImagem2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbRua)
                            .addComponent(lbCep)
                            .addComponent(lbCidade)
                            .addComponent(lbTelefone)
                            .addComponent(lbEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailCampo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(telefoneCampo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cidadeCampo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cepCampo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEndereco)
                                    .addComponent(ruaEnderecoCampo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbNum)
                                        .addGap(6, 6, 6)
                                        .addComponent(numeroEnderecoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(erroImagem3)
                                    .addComponent(erroImagem4)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(salvarBtn)
                        .addGap(69, 69, 69)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbNome)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(erroImagem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCpf)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox1))
                    .addComponent(erroImagem2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruaEnderecoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRua)
                    .addComponent(numeroEnderecoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCep)
                        .addComponent(cepCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(erroImagem4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCidade)
                    .addComponent(cidadeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTelefone)
                        .addComponent(telefoneCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(erroImagem3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(emailCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarBtn)
                    .addComponent(cancelarBtn))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBtnActionPerformed
        String nome = txtNome.getText();
        if (jCheckBox1.isSelected()) {
            pF.setCnpj(txtCpf.getText().replaceAll("[./-]", ""));   
        }
        
        String cpf = txtCpf.getText();
        String endereco = ruaEnderecoCampo.getText();
        String telefone = telefoneCampo.getText();
        pF.setNome(nome);
        pF.setCpf(cpf);
        pF.setEndereco(new Endereco(ruaEnderecoCampo.getText(), 
                                numeroEnderecoCampo.getText(),
                                cepCampo.getText(),
                                cidadeCampo.getText()));
        
        pF.setEmail(emailCampo.getText());
        
        System.out.println(pessoas.constraintViolation(pF));
        //new Pessoas().save(pF);
        
        this.dispose();
    }//GEN-LAST:event_salvarBtnActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void ruaEnderecoCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruaEnderecoCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruaEnderecoCampoActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
            } catch (ParseException ex) {
                Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            try {
                txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
            } catch (ParseException ex) {
                Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        if (!pessoas.getValidador().getValidator().validateValue(Pessoa.class, "nome",
            txtNome.getText()).isEmpty()){
            erroImagem.setVisible(true);
        }
        else {
            erroImagem.setVisible(false);
}
    }//GEN-LAST:event_txtNomeFocusLost

    private void txtCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusLost
        if (jCheckBox1.isSelected()) {
            if (!pessoas.getValidador().getValidator().validateValue(Pessoa.class, "cnpj",
                txtCpf.getText().replaceAll("[.-/]", "")).isEmpty()){
                erroImagem2.setVisible(true);
            }
            else {
                erroImagem2.setVisible(false);
            }
        }
        else {
            if (!pessoas.getValidador().getValidator().validateValue(Pessoa.class, "cpf",
               txtCpf.getText().replaceAll("[.-]", "")).isEmpty()){
               erroImagem2.setVisible(true);
           }
           else {
               erroImagem2.setVisible(false);
           }
        }
        
    }//GEN-LAST:event_txtCpfFocusLost

    private void cepCampoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cepCampoFocusLost
        if (!pessoas.getValidador().getValidator().validateValue(Pessoa.class, "cep",
            cepCampo.getText()).isEmpty()){
            erroImagem4.setVisible(true);
        }
        else {
            erroImagem4.setVisible(false);
        }
    }//GEN-LAST:event_cepCampoFocusLost

    private void telefoneCampoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefoneCampoFocusLost
        if (!pessoas.getValidador().getValidator().validateValue(Pessoa.class, "telefone",
            telefoneCampo.getText()).isEmpty()){
            erroImagem3.setVisible(true);
        }
        else {
            erroImagem3.setVisible(false);
        }
    }//GEN-LAST:event_telefoneCampoFocusLost

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            CadastroCliente dialog = new CadastroCliente(null, true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JFormattedTextField cepCampo;
    private javax.swing.JTextField cidadeCampo;
    private javax.swing.JTextField emailCampo;
    private javax.swing.JLabel erroImagem;
    private javax.swing.JLabel erroImagem2;
    private javax.swing.JLabel erroImagem3;
    private javax.swing.JLabel erroImagem4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel lbCep;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNum;
    private javax.swing.JLabel lbRua;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JTextField numeroEnderecoCampo;
    private javax.swing.JTextField ruaEnderecoCampo;
    private javax.swing.JButton salvarBtn;
    private javax.swing.JFormattedTextField telefoneCampo;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
